language: ruby
gemfile:
   - test/support/Gemfile
rvm:
  - 2.1.1
env:
  - RUNLIST=symfony.json
#cache:
#  directories:
#    - packages
before_install:
  - "wget -N -P packages/ http://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.3.0-1_amd64.deb"
  - "sudo dpkg -i packages/chefdk_0.3.0-1_amd64.deb"
script:
  - bundle exec rake knife
  - bundle exec rake foodcritic
  - bundle exec rake solo
