name             'symfony'
maintainer       'Sergiu Ionescu'
maintainer_email 'sergiu.ionescu@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures symfony'
long_description 'Installs/Configures symfony'
version          '0.1.1'

depends 'php'
depends 'lamp'
depends 'mysql2_chef_gem'
depends 'cron'
depends 'composer'