name             'symfony'
maintainer       'Sergiu Ionescu'
maintainer_email 'sergiu.ionescu@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures symfony'
long_description 'Installs/Configures symfony'
version          '0.1.1'

depends 'lamp', '~> 0.2.1'
depends 'database', '~> 2.3.0'
depends 'php'
depends 'cron', '~> 1.4.0'
depends 'composer', '~> 1.0.5'